# © 2024 Fraunhofer-Gesellschaft e.V., München
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: naming_conventions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  naming_conventions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: extract python version
      uses: ./.github/actions/extract-python-version
    - uses: actions/setup-python@v6
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: install dependencies
      run: |
        # python -m pip install --upgrade pip
        # also see settings in pyproject.toml
        pip install .[dev]  | grep -v 'already satisfied' # The grep part removes "already satisfied" messages from the pip3 install output on linux systems
    - name: naming_conventions
      run: |
        python check/check_naming_conventions.py